"""The committed sample dataset cannot silently rot (I16).

`docs/samples/` is the only artifact of the golden fixture that lives in the
repo (DATA-SPEC §9.5): two studies a reviewer can read without running
anything — `clean-equivalence/` with the live study-wide CSVs the equivalence
gate reproduces byte-for-byte, and `hazard-suite/` with a reconstruction whose
ingestion report itemizes every §9.2 hazard.

A committed artifact generated by code is a liability unless something checks
it still *is* what that code generates, so this module rebuilds both studies
from scratch and compares every byte. Nothing is excluded: the snapshot
builder pins the last two non-deterministic facts the fixture builder leaves
open (the Hub writer's clock and the platform string), so a fresh build is
byte-identical, not merely equivalent-modulo-timestamps.

The build happens under a **temp cwd at the same relative path**, because each
session's config snapshot records the directory it was written to —
reproducibility is per location, and the committed samples are built from the
repo root at `docs/samples/`.

When this module fails, the fix is `python scripts/regenerate_samples.py` plus
a look at the diff — never an edit to a sample file. Two diffs are expected
rather than alarming: a release version bump (the samples stamp
`scoring.__version__` throughout) and a deliberate change to what the
instrument emits, which is exactly the news this test exists to deliver.
"""

from __future__ import annotations

from pathlib import Path

import pytest

from tests.hub.fixture_builder import CLEAN_STUDY, HAZARD_STUDY, tree
from tests.hub.snapshot import REBUILT, SAMPLES, STUDIES, regenerate

# The §9.2 census, imported from the module that owns it rather than restated:
# what the Hub must say about each hazard is I15's subject, and a second copy
# here would be free to disagree with it.
from tests.hub.test_hub_ingestion import HAZARDS, HEADINGS, LOUD_MARKER

REPO_ROOT = Path(__file__).resolve().parents[2]
COMMITTED = REPO_ROOT / SAMPLES

# Every absolute-path root a generating machine could leak into a committed
# file. The samples are built at a relative path precisely so none of these
# can appear (the discipline the screenshots follow).
HOME_ROOTS = ("/Users/", "/home/", "C:\\Users\\", "/private/var/")


@pytest.fixture(scope="module")
def fresh(tmp_path_factory: pytest.TempPathFactory) -> Path:
    """Both studies rebuilt once for the whole module, from a temp directory
    standing in for the repo root — ``regenerate`` moves the cwd there itself,
    so the build lands at the same relative path the committed one did.
    Twenty-odd sessions through the live emission path is the expensive part,
    and every test here only reads the result."""
    return regenerate(tmp_path_factory.mktemp("samples"))


# ── The drift guard ──────────────────────────────────────────────────────────


@pytest.mark.parametrize("study", STUDIES)
def test_the_committed_study_is_byte_identical_to_a_fresh_build(
    fresh: Path, study: str
):
    """The guard itself. Filenames first — a study that gained or lost a file
    is a different failure than one whose contents moved, and the file list is
    what a reader can act on. Then the bytes, file by file, so the assertion
    names the file that drifted rather than dumping the whole tree."""
    built, committed = tree(fresh / study), tree(COMMITTED / study)
    fix = "run `python scripts/regenerate_samples.py` and review the diff"

    assert sorted(committed) == sorted(built), (
        f"{study}: the committed file list differs from a fresh build — {fix}"
    )
    for name, content in built.items():
        assert committed[name] == content, f"{study}/{name} has drifted — {fix}"


# ── What the snapshot must contain (§9.5's two rhetorical jobs) ──────────────


def test_the_clean_study_commits_the_live_output_it_claims(fresh: Path):
    """The **verifiable** half: the clean study is committed as the live
    emission path left it, study-wide CSVs and all. Those CSVs are the
    reference the equivalence gate reproduces, so a snapshot missing them
    would leave the paper's byte-identity claim pointing at nothing. There is
    deliberately no reconstruction here — [T05] §5f requires the *current*
    ``write_output`` to produce both sides of that comparison."""
    names = {path.name for path in (COMMITTED / CLEAN_STUDY).iterdir()}

    assert f"{CLEAN_STUDY}_results.csv" in names
    assert f"{CLEAN_STUDY}_trials.csv" in names
    assert f"{CLEAN_STUDY}_data_dictionary.md" in names
    assert not (COMMITTED / CLEAN_STUDY / REBUILT).exists()


@pytest.mark.parametrize("hazard", HAZARDS, ids=[h.code for h in HAZARDS])
def test_the_committed_report_itemizes_every_planted_hazard(hazard):
    """The **illustrative** half, asserted on the committed bytes rather than
    on a fresh run: a reviewer who opens the sample report sees every §9.2
    hazard, under its severity heading, with the loud tier marked.

    ``test_hub_ingestion.py`` proves the Hub *produces* those lines; this
    proves the artifact in the repo still *carries* them — the claim the paper
    makes about a file, not about a function. The table is imported from that
    module so the two can never disagree about what §9.2 contains."""
    report = (
        COMMITTED / HAZARD_STUDY / REBUILT / f"{HAZARD_STUDY}_ingestion_report.md"
    ).read_text(encoding="utf-8")
    section = report.split(HEADINGS[hazard.group], 1)[1].split("\n## ", 1)[0]

    for fragment in hazard.says:
        assert fragment in section, f"row {hazard.row} ({hazard.what})"
    assert f"- {LOUD_MARKER if hazard.loud else ''}**`{hazard.code}`**" in section


def test_the_samples_leak_no_machine_paths(fresh: Path):
    """Why the relative base is load-bearing. Every sample records the
    directory it was written to, so building at an absolute path would commit
    the generating machine's home directory to the repo — and asserting this
    on the *fresh* build (under a temp cwd nowhere near `docs/`) is what makes
    it a claim about the builder rather than about one lucky run."""
    leaked = [
        f"{path.relative_to(fresh)}: {root}"
        for path in sorted(fresh.rglob("*"))
        if path.is_file()
        for root in HOME_ROOTS
        if root in path.read_text(encoding="utf-8", errors="replace")
    ]

    assert leaked == []


def test_the_samples_record_every_path_posix_separated(fresh: Path):
    """The sibling of the leak guard, and the reason the drift guard was red
    on Windows from I8 to I18. Three producers write a path into a committed
    artifact — the frozen `output_dir`, the reconstruction's source manifest,
    and the finding messages in the ingestion report — and each stringified a
    `Path`, so a Windows build recorded `docs\\samples\\…` against the
    committed `docs/samples/…` and every byte comparison failed at once.

    Asserting it here turns that into a named failure naming the file, rather
    than a byte-diff a reader has to decode. It passes trivially on POSIX,
    which is the point: the machine it can fail on is the one that regressed.
    """
    backslashed = [
        f"{path.relative_to(fresh)}: {line.strip()}"
        for path in sorted(fresh.rglob("*"))
        if path.is_file() and path.suffix in {".json", ".md"}
        for line in path.read_text(encoding="utf-8", errors="replace").splitlines()
        if "\\" in line and "samples" in line
    ]

    assert backslashed == []
